# usb
CONFIG_ZMK_USB=y

# display
CONFIG_MIPI_DBI=y
CONFIG_MIPI_DBI_SPI=y
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096
CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=5
CONFIG_SSD16XX=y

# lvgl
CONFIG_LVGL=y
CONFIG_LV_DPI_DEF=130
CONFIG_LV_COLOR_DEPTH_1=y
CONFIG_LV_Z_BITS_PER_PIXEL=1
CONFIG_LV_Z_VDB_SIZE=10
CONFIG_LV_Z_DOUBLE_VDB=y
CONFIG_LV_Z_FULL_REFRESH=n
CONFIG_LV_Z_MEM_POOL_SIZE=49152
CONFIG_LV_FONT_MONTSERRAT_12=y
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_USE_IMAGE=y
CONFIG_LV_USE_FLEX=y

# split central battery proxy
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# TPS65
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_I2C=y
CONFIG_I2C_NRFX=y
CONFIG_INPUT_THREAD_STACK_SIZE=4096
CONFIG_INPUT_AZOTEQ_IQS5XX=y

# zmk studio
CONFIG_ZMK_STUDIO=y

# hid-indicators CAPS
CONFIG_ZMK_HID_INDICATORS=y
